version: "3.1"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 9090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  redis:
  pgadmin:
