version: "3.1"
services:
  db:
    image: postgres
    container_name: test-db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD

  redis:
    image: redis
    container_name: test-redis
    ports:
      - 6379:6379
