name: Deploy to Staging

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/gcp-deploy.yml
    secrets:
      project: ${{ secrets.GCP_PROJECT_STAGING }}
      provider: ${{ secrets.GCP_PROVIDER_STAGING }}
      service-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STAGING }}
    with:
      environment: "staging"
      service: "application"
      service-region: "asia-southeast1"
      repository: "application-registry"
      repository-region: "asia-southeast1"
