name: Deploy to Staging

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/gcp-deploy.yml
    secrets:
      project: ${{ secrets.GCP_PROJECT }}
      credentials: ${{ secrets.GCP_SA_KEY }}
    with:
      region: "asia-southeast1"
      service: "code-collab-staging"
      repository: "code-collab-staging-repository"
      repository-region: "asia-southeast1"
      # Environment values are case sensitive
      environment: "STAGING"
      node-environment: "staging"
