name: Build and Deploy to Cloud Run Jobs

on:
  workflow_call:
    secrets:
      project:
        description: "Project ID"
        required: true
      provider:
        description: "GCP WIF Provider"
        required: true
      service-account:
        description: "Service Account Email"
        required: true
    inputs:
      environment:
        description: "Application Environment"
        required: true
        type: string
      region:
        description: "Region"
        required: true
        type: string
      job:
        description: "Cloud Run Job ID"
        required: true
        type: string
      repository:
        description: "Artifact Registry"
        required: true
        type: string

permissions:
  contents: "read"
  id-token: "write"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GCP authentication
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.provider }}
          service_account: ${{ secrets.service-account }}

      - name: Docker authentication
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          registry: "${{ inputs.region }}-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Build and push container
        run: |-
          docker build -t "${{ inputs.region }}-docker.pkg.dev/${{ secrets.project }}/${{ inputs.repository }}/${{ inputs.job }}:${{ github.sha }}" -f Serverless.Dockerfile ./
          docker push "${{ inputs.region }}-docker.pkg.dev/${{ secrets.project }}/${{ inputs.repository }}/${{ inputs.job }}:${{ github.sha }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.project }}
          install_components: "beta"

      - name: Deploy to Cloud Run
        run: |
          gcloud beta run jobs update ${{ inputs.job }} \
            --image="${{ inputs.region }}-docker.pkg.dev/${{ secrets.project }}/${{ inputs.repository }}/${{ inputs.job }}:${{ github.sha }}" \
            --region=${{ inputs.region }} \
            --vpc-connector=serverless-vpc-access \
            --vpc-egress=private-ranges-only \
            --task-timeout=1200 \
            --set-env-vars=NODE_ENV=${{ inputs.environment }} \
            --set-secrets=DATABASE_NAME=DATABASE_NAME:latest,DATABASE_USERNAME=DATABASE_USERNAME:latest,DATABASE_PASSWORD=DATABASE_PASSWORD:latest,DATABASE_HOST=DATABASE_HOST:latest,DATABASE_PORT=DATABASE_PORT:latest
